### ISSUE TITLE
Найти hover-стиль для row

### ISSUE THREAD

**Issue by Kerminator1973** [Kerminator1973/ReactDataTables#1]
Искать нужно в стилях -bs5.

**Comment by Kerminator1973** [comment]
```css
table.table.dataTable.table-hover > tbody > tr:hover > * {
  box-shadow: inset 0 0 0 9999px rgba(var(--dt-row-hover), 0.075);
}
table.table.dataTable.table-hover > tbody > tr.selected:hover > * {
  box-shadow: inset 0 0 0 9999px rgba(13, 110, 253, 0.975);
  box-shadow: inset 0 0 0 9999px rgba(var(--dt-row-selected), 0.975);
}
```

**Comment by Kerminator1973** [comment]
Вот решение с `!important`:

```css
table.table.dataTable.table-hover > tbody > tr:hover > * {
    box-shadow: inset 0 0 0 9999px rgba(255, 0, 0, 0.675) !important;
}
```

Нужно понять, как можно сделать тоже самое, но без явного изменение специфичности.
